config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :products
      post '/auth/login', to: "authentication#login"
      get '/homepage', to: "homepage#index"

      post '/orders/mark-order', to: 'orders#mark_order', as: 'mark_order'
      resources :users
      resources :orders

      get '/users/:id/my-cart', to: 'users#show_cart', as: 'show_cart'
      put '/users/:id/add-to-cart/:product_id', to: 'orders#add_to_cart', as: 'add_to_cart'
      put '/users/:id/my-cart/:cart_id/:product_id', to: 'users#remove_from_cart', as: 'remove_from_cart'
      post '/users/:id/my-cart/:cart_id/create-order', to: 'orders#create_order', as: 'create_order'
    end
  end

  get 'sessions/new'

  get '/homepage', to: "homepage#index"
  get '/filter', to: "homepage#index"

  get '/admin', to: "users#show", as: 'admin'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  resources :orders
  post '/users/:id/add-to-cart/:product_id', to: 'orders#add_to_cart', as: 'add_to_cart'
  post '/users/:id/my-cart/:cart_id/create-order', to: 'orders#create_order', as: 'create_order'
  post '/orders/mark-order', to: 'orders#mark_order', as: 'mark_order'
  resources :products
  resources :users
  get '/users/:id/my-cart', to: 'users#show_cart', as: 'show_cart'
  get '/users/:id/show-orders', to: 'users#show_orders', as: 'show_orders'
  post '/users/:id/my-cart/:cart_id/:product_id', to: 'users#remove_from_cart', as: 'remove_from_cart'
  get '/users/:id/show-orders/details', to: 'users#show_order_details', as: 'show_order_details'
  post '/users/make-admin', to: 'users#make_admin', as: 'make_admin'

  # Defines the root path route ("/")
  root "homepage#index"
end

app/controllers/api/v1/homepage_controller.rb
class Api::V1::HomepageController < Api::V1::BaseController
  before_action :authorize_request
  
  def index
    @homepage = true

    if logged_in?
      @cart = Order.find_by("user_id = ? AND is_cart = ?", @current_user.id, true)
    end
    
    products = Product.all

    products = products.where("category = ?", Product.categories[params[:category]]) if params[:category].present? && params[:category] != 'none'
    if params[:sorting].present? && params[:sorting] != 'none'
      if params[:sorting] == 'az'
        products = products.order(:name)
      elsif params[:sorting] == 'za'
        products = products.order(name: :desc)
      elsif params[:sorting] == 'ascending-price'
        products = products.order(:price)
      elsif params[:sorting] == 'descending-price'
        products = products.order(price: :desc)
      end
    end
    products = products.where(vegetarian: (params[:vegetarian_select] == 'vegetarian')) if params[:vegetarian_select].present? && params[:vegetarian_select] != 'none'
 
    products = products.where("price >= ? AND price <= ?", params[:min_price].to_i, params[:max_price].to_i) if params[:min_price].present? && params[:max_price].present?

    render json: ProductSerializer.new(products).serialize, status: :ok
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @homepage = true

    if logged_in?
      @cart = Order.find_by("user_id = ? AND is_cart = ?", @current_user.id, true)
    end
    
    @products = Product.all

    @products = @products.where("category = ?", Product.categories[params[:category]]) if params[:category].present? && params[:category] != 'none'
    if params[:sorting].present? && params[:sorting] != 'none'
      case params[:sorting]
        when 'az'
          @products = @products.order(:name)
        when 'za'
          @products = @products.order(name: :desc)
        when 'ascending-price'
          @products = @products.order(:price)
        when 'descending-price'
          @products = @products.order(price: :desc)
      end
    end
    @products = @products.where(vegetarian: (params[:vegetarian_select] == 'vegetarian')) if params[:vegetarian_select].present? && params[:vegetarian_select] != 'none'
 
    @products = @products.where("price >= ? AND price <= ?", params[:min_price].to_i, params[:max_price].to_i) if params[:min_price].present? && params[:max_price].present?
  end

end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/_footer.html.haml
%footer
  .footer-container
    .contacts-container
      .pair#facebook
        %a{:href => "https://www.facebook.com/"}
          %img.social-media-icon{:src => "#{image_path('facebook-icon.png')}"}
        %p.social-media.center-to-icon facebook contact


      .pair#instagram
        %a{:href => "https://www.instagram.com/"}
          %img.social-media-icon{:src => "#{image_path('insta-icon.png')}"}
        %p.social-media.center-to-icon instagram contact


      .pair#mail
        %a{:href => "https://www.gmail.com/"}
          %img.social-media-icon{:src => "#{image_path('mail-icon.png')}"}
        %p.social-media.center-to-icon contact@office.com

    .credits-container
      %p.credits-text#credits © To the people that took those photos

app/views/homepage/_header.html.haml
%header
  .logo-navbar
    = link_to root_path do
      .logo
        %img.logo-icon{:src => "#{image_path('logo.png')}"}
        %figcaption#logo-text EUREKA CAFFE

    #navbar
      %ul.navbar
        %li.navbar.navbar-item
          = link_to 'HOME', root_path

        %li.navbar.dot •

        %li.navbar.navbar-item
          %a{:href => "#"}ABOUT

        %li.navbar.dot •

        %li.navbar.navbar-item
          %a{:href => "#"}SERVICE
        
        %li.navbar.dot •

        %li.navbar.navbar-item
          %a{:href => "#"}BLOG
        
        %li.navbar.dot •

        %li.navbar.navbar-item
          %a{:href => "#"}CONTACTS

        - if logged_in?
          %li.navbar.dot •

          %li.navbar.navbar-item.profile-dropdown
            %button.profile-drop-button
              HELLO, 
              = @current_user.name.upcase
              %img.user-profile-icon{:src => "#{image_path('user-icon.png')}"}
            .profile-drop-content
              - if @current_user.user?
                = link_to 'My profile', user_path(@current_user)
              - else 
                = link_to 'My dashboard', admin_path
              = link_to 'My Orders', show_orders_path(@current_user.id)
              = link_to 'Log Out', logout_path
          
        - else
          %li.navbar.dot •

          %li.navbar.navbar-item
            = link_to "LOGIN", login_path 

  - if @homepage && !@signup && !@login
    .main-message
      %h1.main-message-text Ordering food

      %hr.white-line

      %p#slogan Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

      %br
      %br

app/views/homepage/index.html.haml
= render 'homepage/header'
.body-container
  = form_with(url: '/filter', method: :get, html: { class: "filters-container" }) do |form|
    .dropdown-menus-container
      .dropdown-menu-display#dropdown-category
        %button.drop-button CATEGORY
        %img.dropdown-arrow{:src => image_path('dropdown-arrow.png')} 

        .dropdown-content
          = form.hidden_field :category, value: 'none'
          .dropdown-item#entree{:value => "entree"} Entrées
          .dropdown-item#second-course{:value => "second_course"} Second Course
          .dropdown-item#dessert{:value => "dessert"} Desserts

      .dropdown-menu-display#dropdown-sorting
        %button.drop-button SORTING
        %img.dropdown-arrow{:src => image_path('dropdown-arrow.png')}

        .dropdown-content
          = form.hidden_field :sorting, value: 'none'
          .dropdown-item#az{:value => "az"} A to Z
          .dropdown-item#za{:value => "za"} Z to A
          .dropdown-item#ascending-price{:value => "ascending-price"} Ascending Price
          .dropdown-item#descending-price{:value => "descending-price"} Descending Price
          
      .dropdown-menu-display#dropdown-vegetarian
        %button.drop-button VEGETARIAN
        %img.dropdown-arrow{:src => image_path('dropdown-arrow.png')} 

        .dropdown-content
          = form.hidden_field :vegetarian_select, value: 'none'
          .dropdown-item#vegetarian{:value => "vegetarian"} Vegetarian
          .dropdown-item#non-vegetarian{:value => "non-vegetarian"} Non-Vegetarian

    .price-range-container
      %p.price-range-item.price PRICE

      %p.price-range-item.price#min-slider
      = form.hidden_field :min_price, value: '5'

      #uislider

      %p.price-range-item.price#max-slider
      = form.hidden_field :max_price, value: '85'

    = form.submit "APPLY FILTERS", class: "apply-filters-button"
    
    = link_to "RESET FILTERS", root_path, class: "reset-filters-link"

  - if logged_in?
    .basket-container
      = link_to image_tag(image_path('basket-icon'), class: "cart-icon"), show_cart_path(@current_user.id)
      %p View cart
      - if !@cart.nil? && !@cart.order_products.empty?
        %p.bg-warning.p-2
          = @cart.order_products.length
  
  .food-items-container
    .border-wrapper
      - @products.each do |product|
        .food-item
          = cl_image_tag(product.image.url, class: "food-image")

          %p.food-name=product.name

          - if product.category == "no_category"
            %p.food-category Others
          - elsif product.category == "entree"
            %p.food-category Entrée
          - elsif product.category == "second_course"
            %p.food-category Second Course
          - elsif product.category == "dessert"
            %p.food-category Dessert

          %p.food-price="$#{number_with_precision(product.price, precision: 2)}"

          - if logged_in?
            = form_with(url: add_to_cart_path(@current_user.id, product.id), method: :post, html: {class: "add-to-cart-form"}) do |form|
              = form.number_field :quantity, value: 1, min: 1, step: 1
              = form.submit "", type: :image, src: image_path('cart-icon.png'),  class: "add-to-cart-button cart-icon"