config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :products
      post '/auth/login', to: "authentication#login"
      get '/homepage', to: "homepage#index"

      post '/orders/mark-order', to: 'orders#mark_order', as: 'mark_order'
      resources :users
      resources :orders

      get '/users/:id/my-cart', to: 'users#show_cart', as: 'show_cart'
      put '/users/:id/add-to-cart/:product_id', to: 'orders#add_to_cart', as: 'add_to_cart'
      put '/users/:id/my-cart/:cart_id/:product_id', to: 'users#remove_from_cart', as: 'remove_from_cart'
      post '/users/:id/my-cart/:cart_id/create-order', to: 'orders#create_order', as: 'create_order'
    end
  end

  get 'sessions/new'

  get '/homepage', to: "homepage#index"
  get '/filter', to: "homepage#index"

  get '/admin', to: "users#show", as: 'admin'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  resources :orders
  post '/users/:id/add-to-cart/:product_id', to: 'orders#add_to_cart', as: 'add_to_cart'
  post '/users/:id/my-cart/:cart_id/create-order', to: 'orders#create_order', as: 'create_order'
  post '/orders/mark-order', to: 'orders#mark_order', as: 'mark_order'
  resources :products
  resources :users
  get '/users/:id/my-cart', to: 'users#show_cart', as: 'show_cart'
  get '/users/:id/show-orders', to: 'users#show_orders', as: 'show_orders'
  post '/users/:id/my-cart/:cart_id/:product_id', to: 'users#remove_from_cart', as: 'remove_from_cart'
  get '/users/:id/show-orders/details', to: 'users#show_order_details', as: 'show_order_details'
  post '/users/make-admin', to: 'users#make_admin', as: 'make_admin'

  # Defines the root path route ("/")
  root "homepage#index"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :orders, dependent: :delete_all

  enum role: {
    user: 0,
    admin: 1
  }

  before_save { self.email = email.downcase }  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def session_token
    remember_digest || remember
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  include UsersHelper
  before_action :authorize_request, except: :create
  before_action :has_role_user?, only: [:show_carts]
  before_action :has_role_admin?, only: :index

  def index
    users = User.all

    render json: UserSerializer.new(users).serialize, status: :ok
  end

  def show 
    @user = User.find(params[:id])
  end

  def new
    @signup = true
    @user = User.new
  end

  def create
    user = User.create!(user_params)

    render json: UserSerializer.new(user).serialize, status: :created
  rescue ActiveRecord::RecordNotSaved
    render json: { error: "unprocessable_entity" }, status: :unprocessable_entity
  end

  def show_cart
    @user = User.find(params[:id])
    cart = Order.find_by("user_id = ? AND is_cart = ?", @user.id, true)
    
    if !cart.nil?
      render json: ProductSerializer.new(cart.products).serialize, status: :ok
    else
      head :no_content
    end
  end

  def remove_from_cart
    cart = Order.find(params[:cart_id])
    product_id = params[:product_id].to_i
    @quantities = update_quantities(cart, product_id)
    @order_product = cart.order_products.find_by("product_id = ?", product_id)

    if @quantities[product_id] == 0
      cart.order_products.destroy(@order_product)
    else
      @order_product.update(quantity: @quantities[product_id])
    end

    render json: ProductSerializer.new(cart.products).serialize, status: :ok
  end

  def show_orders
    @user = User.find(params[:id])
    @orders = Order.where("user_id = ?", params[:id])
  end

  def show_order_details
    @order = Order.find(params[:order_id])

    @products = get_order_products(@order)
    @total = compute_cart_total(@order)
    @quantities = compute_quantities(@order)
  end

  def make_admin
    @user = User.find(params[:user_id].to_i)

    if @user.update_attribute(:role, 1)
      redirect_to users_path
    end
  end

  private
    def user_params
      params.permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def index
    if current_user.admin?
      @users = User.all
    else
      redirect_to root_path
    end
  end

  def show
    if current_user.present?
      if current_user.admin?
        render 'admin/index'
      else
        render 'users/show'
      end
    else
      redirect_to root_path
    end
  end

  def new
    @signup = true
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      login @user
      flash[:success] = "Welcome to Food Ordering App!"
      
      redirect_to @user
    else
      render 'new'
    end
  end

  def show_cart
    @user = User.find(params[:id])
    @cart = Order.find_by("user_id = ? AND is_cart = ?", @user.id, true)
    if !@cart.nil?
      @products = get_users_products(@cart)
      @total = compute_cart_total(@cart)
      @quantities = compute_quantities(@cart)
    end
  end

  def remove_from_cart
    @cart = Order.find(params[:cart_id])
    product_id = params[:product_id].to_i
    @quantities = update_quantities(@cart, product_id)
    @order_product = @cart.order_products.find_by("product_id = ?", product_id)

    if @quantities[product_id] == 0
      @cart.order_products.destroy(@order_product)
    else
      @order_product.update(quantity: @quantities[product_id])
    end

    redirect_to show_cart_path
  end

  def show_orders
    @user = User.find(params[:id])
    @orders = Order.where("user_id = ?", params[:id])
  end

  def show_order_details
    @order = Order.find(params[:order_id])

    @products = get_order_products(@order)
    @total = compute_cart_total(@order)
    @quantities = compute_quantities(@order)
  end

  def make_admin
    @user = User.find(params[:user_id].to_i)

    if @user.update_attribute(:role, 1)
      redirect_to users_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?=s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def is_admin?(user)
    return (user.admin?)
  end

  def get_users_products(cart)
    products = []
    cart.order_products.each do |order_product|
      products.push(Product.find(order_product.product_id))
    end
    
    return products
  end

  def compute_cart_total(cart)
    total = 0.0
    cart.order_products.each do |order_product|
      product = Product.find(order_product.product_id)
      total = total + (product.price * order_product.quantity)
    end
    
    return total
  end

  def compute_quantities(cart)
    quantities = []
    cart.order_products.each do |order_product|
      quantities[order_product.product_id] = order_product.quantity
    end

    return quantities
  end

  def update_quantities(cart, product_id)
    quantities = []
    cart.order_products.each do |order_product|
      if order_product.product_id == product_id
        order_product.quantity = order_product.quantity - 1
      end
      quantities[order_product.product_id] = order_product.quantity
    end

    return quantities
  end

  def get_order_products(order)
    products = []
    order.order_products.each do |order_product|
      products.push(Product.find(order_product.product_id))
    end

    return products
  end
end

app/views/users/index.html.haml
= render 'admin/navbar'
.p-4
  = link_to "New user?", root_path, class: "btn btn-warning"
  %ul.list-group.pt-2
  - @users.each do |user|
    %li.list-group-item.border.border-secondary.rounded.p-3.d-flex.flex-column
      %p #{user.name}
      %p #{user.email}
      - if user.role == "admin"
        %p.text-danger ADMIN
      = link_to "Edit", root_path, class: "btn btn-primary"
      = button_to "Make admin", make_admin_path(user_id: user.id), method: :post, class: "btn btn-info"

app/views/users/new.html.haml
= render 'homepage/header'
.login-container
  %h1.main-message-text Sign Up
  .login-form-container
    = form_with(model: @user, local: true) do |f|
      = render 'shared/error_messages'
      = f.label :name, class: 'form-element'
      = f.text_field :name, class: 'form-control form-element', placeholder: "John Doe"
      = f.label :email, class: 'form-element'
      = f.email_field :email, class: 'form-control form-element', placeholder: "john.doe@example.com"
      = f.label :password, class: 'form-element'
      = f.password_field :password, class: 'form-control form-element', placeholder: "••••••"
      = f.label :password_confirmation, "Confirmation", class: 'form-element'
      = f.password_field :password_confirmation, class: 'form-control form-element'
      %br
      = f.submit "Create Account", class: "btn btn-primary"

app/views/users/show.html.haml
= render 'homepage/header'
%body
  .info-container
    %h1.first-name
      = gravatar_for(current_user)
      = current_user.name
    .details-container
      .email-field
        Email: #{current_user.email}

    .buttons-container
      %button.edit-button EDIT
      %button.edit-button DELETE

app/views/users/show_cart.html.haml
= render 'homepage/header'
%h1.cart-title
  = @current_user.name + '\'s cart'
%br

- if @cart.nil?
  %h2.cart-title You currently have nothing stored in the cart
- else
  %ul
    - @products.each do |product|
      %li.cart-item
        = cl_image_tag(product.image.url, class: "float-left img-product")
        %p.cart-text
          = product.name
        %p.cart-text
          - if product.category == "no_category"
            No category 
          - elsif product.category == "entree"
            Entrée
          - elsif product.category == "second_course"
            Second course
          - elsif product.category == "dessert"
            Dessert
        %p.cart-text Price per unit: #{number_with_precision(product.price, precision: 2)}
        
        %p.cart-text Quantity: #{@quantities[product.id]}

        %p.cart-text Product total: #{number_with_precision(product.price * @quantities[product.id].to_i, precision: 2) }

        %br

        = button_to "Remove", remove_from_cart_path(@current_user.id, @cart.id, product.id), class: "btn btn-danger"

  %p.cart-text Total: #{number_with_precision(@total, precision: 2)}
  = button_to "Place order", create_order_path(@current_user.id, @cart.id, total: @total), class: "btn btn-primary"

app/views/users/show_order_details.html.haml
= render 'homepage/header'
%h1.cart-title #{@current_user.name}'s order ##{@order.id}
%br
%ul
  - @products.each do |product|
    %li.cart-item
      = cl_image_tag(product.image.url, class: "float-left img-product")
      %p.cart-text
        = product.name
      %p.cart-text
        - if product.category == "no_category"
          No category 
        - elsif product.category == "entree"
          Entrée
        - elsif product.category == "second_course"
          Second course
        - elsif product.category == "dessert"
          Dessert
      %p.cart-text Price per unit: #{number_with_precision(product.price, precision: 2)}
      
      %p.cart-text Quantity: #{@quantities[product.id]}

      %p.cart-text Product total: #{number_with_precision(product.price * @quantities[product.id].to_i, precision: 2) }

      %br

%p.cart-text Total: #{number_with_precision(@total, precision: 2)}

app/views/users/show_orders.html.haml
- if logged_in?
  - if @current_user.id == @user.id
    = render 'homepage/header'
    %h1.cart-title #{@current_user.name + '\'s orders'}
    %br
    - if @orders.length == 0
      %h2.cart-title You currently have no orders
    - else
      %ul
        - @orders.each do |order|
          %li.cart-item
            %p.cart-text Order with ID: #{order.id}
            %p.cart-text Total: #{order.total}

            = link_to "View order details", show_order_details_path(order_id: order.id), class: "btn btn-secondary"
  - else
    :javascript
      window.location.href="/"

      