config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :products
      post '/auth/login', to: "authentication#login"
      get '/homepage', to: "homepage#index"

      post '/orders/mark-order', to: 'orders#mark_order', as: 'mark_order'
      resources :users
      resources :orders

      get '/users/:id/my-cart', to: 'users#show_cart', as: 'show_cart'
      put '/users/:id/add-to-cart/:product_id', to: 'orders#add_to_cart', as: 'add_to_cart'
      put '/users/:id/my-cart/:cart_id/:product_id', to: 'users#remove_from_cart', as: 'remove_from_cart'
      post '/users/:id/my-cart/:cart_id/create-order', to: 'orders#create_order', as: 'create_order'
    end
  end

  get 'sessions/new'

  get '/homepage', to: "homepage#index"
  get '/filter', to: "homepage#index"

  get '/admin', to: "users#show", as: 'admin'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  resources :orders
  post '/users/:id/add-to-cart/:product_id', to: 'orders#add_to_cart', as: 'add_to_cart'
  post '/users/:id/my-cart/:cart_id/create-order', to: 'orders#create_order', as: 'create_order'
  post '/orders/mark-order', to: 'orders#mark_order', as: 'mark_order'
  resources :products
  resources :users
  get '/users/:id/my-cart', to: 'users#show_cart', as: 'show_cart'
  get '/users/:id/show-orders', to: 'users#show_orders', as: 'show_orders'
  post '/users/:id/my-cart/:cart_id/:product_id', to: 'users#remove_from_cart', as: 'remove_from_cart'
  get '/users/:id/show-orders/details', to: 'users#show_order_details', as: 'show_order_details'
  post '/users/make-admin', to: 'users#make_admin', as: 'make_admin'

  # Defines the root path route ("/")
  root "homepage#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products, dependent: :delete_all
  has_one_attached :image
  
  enum category: {
    no_category: 0,
    entree: 1,
    second_course: 2,
    dessert: 3
  }
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::BaseController
  before_action :authorize_request
  before_action :has_role_admin?, except: :index

  def index
    products = Product.all
    render json: ProductSerializer.new(products).serialize
  end

  def new
    @categories = Product.categories.keys
    @product = Product.new
  end

  def create
    product = Product.create!(product_params)
      
    render json: ProductSerializer.new(product).serialize, status: :created
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Product.categories.keys
  end

  def update
    product = Product.find(params[:id])
    product.update!(product_params)
    
    render json: ProductSerializer.new(product).serialize, status: :ok
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy!

    head :ok
  rescue ActiveRecord::RecordNotDestroyed
    render json: { error: 'unprocessable_entity' }, status: :unprocessable_entity
  end

  private
    def product_params
      params.permit(:name, :price, :vegetarian, :category, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if current_user.admin?
      @products = Product.all
    else 
      redirect_to root_path
    end
  end

  def new
    if current_user.admin?
      @categories = Product.categories.keys
      @product = Product.new
    else 
      redirect_to root_path
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Successfully created the product #{@product.name}!"
      
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    if current_user.admin?
      @product = Product.find(params[:id])
      @categories = Product.categories.keys
    else
      redirect_to root_path
    end
  end

  def update
    product = Product.find(params[:id])
    if product.update(product_params)
      flash[:success] = "Product updated successfully!"

      redirect_to edit_product_path
    else
      flash[:danger] = "Update failed. Try again!"

      render 'edit'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product with #{params[:id]} successfully deleted!"

    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :vegetarian, :description, :image, :category)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.haml
= render 'admin/navbar'
%h1 Edit product page
= form_with(url: product_path(@product.id), model: @product, method: :patch, html: { class: "p-4" }) do |form|
  .form-group
    = form.label :name
    = form.text_field :name, class: "form-control", value: "#{@product.name}"
  .form-group
    = form.label :price
    = form.text_field :price, class: "form-control", value: "#{number_with_precision(@product.price, precision: 2)}"
  .form-group
    = form.check_box :vegetarian, value: "#{@product.vegetarian}"
    = form.label :vegetarian
  .form-group
    = form.label :category
    = form.select :category, @categories, class: "form-control", selected: @product.category
  .form-group
    = form.label :description
    = form.text_area :description, class: "form-control", value: "#{@product.description}"
  .form-group
    = form.label "Please reintroduce the picture you want for this product"
    = form.file_field :image, src: "#{@product.image}"

  = form.submit "Edit product", class: "btn btn-primary mt-3"

app/views/products/index.html.haml
= render 'admin/navbar'
.p-4
  = link_to "New product", new_product_path, class: "btn btn-warning"
  %ul.list-group.p-4
  - @products.each do |product|
    %li.list-group-item.border.border-secondary.rounded.p-3.d-flex.flex-column
      = cl_image_tag(product.image.url, class: "float-left img-product")
      %p 
        = product.name
      %p 
        = product.category
      %p 
        = number_with_precision(product.price, precision: 2)

      - if product.vegetarian
        %p.bg-success Vegetarian
      = link_to "Edit", edit_product_path(product.id), class: "btn btn-primary"
      = button_to "Delete", product_path(product.id), method: :delete, class: "btn btn-danger"

app/views/products/new.html.haml
= render 'admin/navbar' 
%h1 Create a new product
= form_with(model: @product, html: { class: "p-4" }) do |form|
  .form-group
    = form.label :name
    = form.text_field :name, class: "form-control", placeholder: "Pizza Senorita"
  .form-group
    = form.label :price
    = form.text_field :price, class: "form-control", placeholder: "12.34"
  .form-group
    = form.label :category
    = form.select :category, @categories, class: "form-control"
  .form-group
    = form.check_box :vegetarian
    = form.label :vegetarian
  .form-group
    = form.label :description
    = form.text_area :description, class: "form-control", placeholder: "Write a description for your product"
  .form-group
    = form.file_field :image

  = form.submit "Create product", class: "btn btn-primary mt-3"